title: jekyll-github-pages
email: jekyll-github-pages@example.com
description: >-
  This page is using Jekyll.
baseurl: "/jekyll-github-pages"
url: "https://s-sato-1.github.io"
twitter_username: jekyll-github-pages
github_username:  jekyll-github-pages
theme: minima
plugins:
  - jekyll-feed
